# Generated by Django 4.2.7 on 2023-11-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='data',
        ),
    ]
